### PR TITLE
there is something wrong with the siamese_data_trian_test.py

### PR DESCRIPTION
**Pull request by ghost**
I cannot run your code , there is something wrong with the siamese_data_trian_test.py. Thanks!

### CODE REVIEW

**Comment by suderoy** [comment]
There's sometime issues based on your tab size in spaces and editor used. If you checkout the code it should not be the case though. Please align it according to your editor's settings. Unfortunately, this one works fine with my editor.

**Comment by ghost** [comment]
Hi, Thanks for your reply.
The problem is the 'load_data' function should return 3 variables, however it did not.
So I guessed you may miss a 'return' line in the load_data function 
Thanks very much

**Comment by ghost** [comment]
Hi，
Thanks for your reply !
My problem here is the 'load_data' function should return 3 variables,
however , in your code, the load_data function seems missing a 'return'
line.
Thanks
best,
Jieyi
[image: Screen Shot 2019-02-15 at 21.48.31.png]

**Comment by suderoy** [comment]
Hi, Thank you for pointing out. I have added the missing return statement

**Comment by ghost** [comment]
Thanks a lot!

**Pull request closed without merging**
